"""empty message

Revision ID: 1008c33ec2c6
Revises: 50749b6e8b1b
Create Date: 2022-11-05 16:49:48.907331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1008c33ec2c6'
down_revision = '50749b6e8b1b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tags', 'users', ['user_id'], ['id'])
    op.drop_constraint('users_tag_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'tag_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_tag_id_fkey', 'users', 'tags', ['tag_id'], ['id'])
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.drop_column('tags', 'user_id')
    # ### end Alembic commands ###
